### PR TITLE
[WIP] Code a tool to collect docstrings for the reference

### PR DESCRIPTION
**Pull request by NathanLovato**
For #10 

- Add some regex to capture types and values for functions and properties.
- Write some skeleton functions to collect relevant statements and lines for the reference.

### CODE REVIEW

**Comment by NathanLovato** [comment]
At this state the reference data looks like this:
```
[{'GSTTargetAcceleration': {'function': [{'arguments': [],
                                          'docstring': 'Resets the '
                                                       'accelerations to zero',
                                          'name': 'reset',
                                          'type': 'void'},
                                         {'arguments': [],
                                          'docstring': '',
                                          'name': 'add_scaled_accel',
                                          'type': 'void'},
                                         {'arguments': [],
                                          'docstring': '',
                                          'name': 'get_magnitude_squared',
                                          'type': 'float'},
                                         {'arguments': [],
                                          'docstring': '',
                                          'name': 'get_magnitude',
                                          'type': 'float'}],
                            'property': [{'docstring': 'Linear acceleration',
                                          'getter': '',
                                          'identifier': 'linear',
                                          'setter': '',
                                          'type': None,
                                          'value': 'Vector3.ZERO'},
                                         {'docstring': 'Angular acceleration',
                                          'getter': '',
                                          'identifier': 'angular',
                                          'setter': '',
                                          'type': None,
                                          'value': '0.0'}],
                            'signal': [],
                            'subclass': [{'docstring': '', 'name': ''}]}}]
```

**Comment by NathanLovato** [comment]
@Razoric480 I should probably move this to its own repository, no?
At this stage, the tool can already collect the identifiers, types, setget functions, and docstrings. The function arguments need a fix, and it needs some extra code for the class name and class docstring, but it's close to being ready. All you have to do to document your code is add comments:

```gdscript
class_name GSTTargetAcceleration
# A linear and angular amount of acceleration.


# Linear acceleration
var linear: = Vector3.ZERO
# Angular acceleration
var angular: = 0.0


# Resets the accelerations to zero
func reset() -> void:
	linear = Vector3.ZERO
	angular = 0.0


func add_scaled_accel(accel: GSTTargetAcceleration, scalar: float) -> void:
	linear += accel.linear * scalar
	angular += accel.angular * scalar
```

**Comment by Razoric480** [comment]
Yeah, it probably should be its own repository, given it's intended to be used with more than just this API :) and other people would probably find this all too useful.

And sounds good. I'll open a new branch to start spreading docstring comments accordingly.

**Comment by Razoric480** [comment]
@NathanLovato What about functions with parameters? Do they have any special docstring, or should the parameters just be explained if required?

**Comment by NathanLovato** [comment]
> What about functions with parameters?

I would go with explaining only if necessary. Like in `apply_scale(factor)`, the argument is self-explanatory.
To explain more about the function in the docstring, I'd say let's go with something similar to Python's docstring conventions.

For simple docs, use one line docstrings:

```
# Movement speed of the character in meters per second
var speed: = 0.0
```

This also applies to functions when the arguments are self-explanatory:

```
# Scales the object by `factor`
func apply_scale(factor: float) -> void:
```

When the arguments are trickier or need explanation, I'd suggest something like this:
```gdscript
# Returns a Path object that describes the nodes to navigate between the `from`
# and `to` positions. If it cannot find a path, returns an empty `Path` object.
# 
# **Arguments**
# 
# - from: starting position to find a path from
# - to: end position to find a path to
# - algorithm: any object that extends `Pathfinder` and defines the virtual method `_find_path`. See `PathfinderAStar` and `PathfinderHeatMap` for two predefined examples.
func find_path(from: Vector3, to: Vector3, algorithm: Pathfinder) -> Path:
```

Here, I've used markdown for the markup.

In any case, we can create a snippet to write the functions with the docstrings in this particular format directly.

**Comment by NathanLovato** [comment]
The tool is ready to use to extract the JSON data, it's in its own repository: https://github.com/GDQuest/gdscript-docs-maker

**Pull request closed without merging**
